[package]
name = "pam-rust-oidc"
version = "0.2.4"
edition = "2021"
license = "MIT"
description = "Linux PAM module using an OIDC Credentials.Verify API"

[lib]
name = "pam_rust_oidc"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22"
jsonwebtoken = "9"
libc = "0.2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
sha1 = "0.10"
toml = "0.8"
x509-parser = "0.16"
uuid = { version = "1", features = ["v4"] }
zeroize = "1"

[profile.release]
lto = true
codegen-units = 1
